info:
  version: 1.0.0
  description: Routing information for UE

ueRoutingInfo:
  - SUPI: imsi-2089300007487
    AN: 192.168.2.157
    PathList:
      - DestinationIP: 192.168.2.54
        UPF: !!seq
          - UPF1
          - UPF1

      - DestinationIP: 192.168.2.219
        UPF: !!seq
          - UPF2
          - UPF2
      
      - DestinationIP: 192.168.2.23
        UPF: !!seq
          - UPF3
          - UPF3

  - SUPI: imsi-2089300007486
    AN: 10.200.200.102
    PathList:
      - DestinationIP: 10.0.0.10
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF1

      - DestinationIP: 10.0.0.11
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF2
  - SUPI: imsi-2089300007485
    AN: 10.200.200.102
    PathList:
      - DestinationIP: 10.0.0.10
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF1

      - DestinationIP: 10.0.0.11
        UPF: !!seq
          - BranchingUPF
          - AnchorUPF2

routeProfile:
  MEC1:
    forwardingPolicyID: 10

pfdDataForApp:
  - applicationId: edge
    pfds:
      - pfdID: pfd1
        flowDescriptions:
          - permit out ip from 60.60.0.1 8080 to any
