info:
  version: 1.0.0
  description: Routing information for UE

ueRoutingInfo:
  - SUPI: imsi-2089300007487
    AN: 192.168.2.157
    PathList:
      - DestinationIP: 192.168.2.111
        UPF: !!seq
          - UPF4
          - UPF1
      - DestinationIP: 192.168.2.112
        UPF: !!seq
          - UPF4
          - UPF2
      - DestinationIP: 192.168.2.113
        UPF: !!seq
          - UPF4
          - UPF3
      

  - SUPI: imsi-2089300007488
    AN: 192.168.2.150
    PathList:
      - DestinationIP: 192.168.2.219
        UPF: !!seq
          - UPF2
          - UPF5
      - DestinationIP: 192.168.2.54
        UPF: !!seq
          - UPF1
          - UPF4
      - DestinationIP: 192.168.2.23
        UPF: !!seq
          - UPF3
          - UPF6
  
  #- SUPI: imsi-2089300007487
    #AN: 192.168.2.25
    #PathList:
      #- DestinationIP: 192.168.2.23
        #UPF: !!seq
          #- UPF3
          #- UPF6
      #- DestinationIP: 192.168.2.54
        #UPF: !!seq
          #- UPF1
          #- UPF4
      #- DestinationIP: 192.168.2.219
       # UPF: !!seq
          #- UPF2
          #- UPF5

routeProfile:
  MEC1:
    forwardingPolicyID: 10

pfdDataForApp:
  - applicationId: edge
    pfds:
      - pfdID: pfd1
        flowDescriptions:
          - permit out ip from 60.60.0.1 8080 to any
